# Generated by Django 3.0.7 on 2020-06-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='shared_key',
            new_name='shared_secret',
        ),
    ]
