# Generated by Django 3.0.7 on 2020-06-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_auto_20200609_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='msj',
        ),
    ]
