# Generated by Django 3.0.7 on 2020-06-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_auto_20200609_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='msj',
            new_name='msg',
        ),
    ]
